
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: my-app-cluster
  annotations:
    crossplane.io/external-name: my-app-cluster-dev  
spec:
  writeConnectionSecretToRef:
    name: my-app-cluster-dev-secret
  location: "North Europe"
  aks:
    adminUser: b99ec8cd-2cb4-4028-a385-0c422873022d
    tags:
      environment: dev
  virtualNetwork:
    tags:
      environment: dev   
